### ISSUE TITLE
Document agent specializations

### ISSUE THREAD

**Issue by Kvikal** [ghollies/Rising-Constellation-FAQ#3]
I believe current agent specializations (Hacker, Analyst, Butcher...) are not documented and I think it would be a good addition.
I am not 100% sure on which exact skills are prefered for each specialization but somebody with more experience would probably know them all.

Simple table on each agent type would be great to quickly lookup what each specialization means.

-- Haestrom

**Comment by ghollies** [comment]
added as part of 700997716bd374a4449ab29e41b7bb600e0f575b ! great idea. also made the official infographics more visible on each agent type's page.
let me know what you think
